Style/RedundantReturn:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 80
Metrics/AbcSize:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody: 
  Enabled: false

Style/AsciiComments:
  Enabled: false
